### ISSUE TITLE
Observation selection takes a long time and times out

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-ObservationsDatabase#73]
Hi Tim,

I've noticed some niggles with the Import Batch observation selections. If one clicks the tick box that is supposed to highlight all the records on the page it takes forever to process the selection and often times out eventually. I hope there is a remedy for this because I think there are other Nodes with connections that are even slower than ours.

![image](https://cloud.githubusercontent.com/assets/8395262/25942573/88b89266-363d-11e7-91ae-d9ce55e18806.png)

**Comment by TimPN-SAEON** [comment]
I have managed to fixed this, please check and close if you are happy.

**Comment by Abrisaeon** [comment]
Brilliant! That's much better!
